services:
  web:
    build: .
    # Still uses runserver for local development with live reloading
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # Mounts local code into container for live updates
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Environment variables needed by the simplified settings.py
      # These MUST match the credentials used by the 'db' service below.
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db # The service name of the database container
      - DATABASE_PORT=5432
      # SECRET_KEY is now hardcoded in settings.py (for local dev only)
      # DJANGO_DEBUG is now hardcoded in settings.py (for local dev only)
      # DATABASE_URL is no longer used by this simplified settings.py

  db:
    image: postgres:16
    restart: always
    environment:
      # Environment variables for the PostgreSQL container itself
      POSTGRES_DB: postgres # Should match DATABASE_NAME above
      POSTGRES_USER: postgres # Should match DATABASE_USER above
      POSTGRES_PASSWORD: postgres # Must match DATABASE_PASSWORD above
    ports:
      # Optional: Expose port to host if you need to connect directly
      - "5432:5432"
    volumes:
      # Persist database data locally
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# Restartē konteinerus
# docker-compose restart

# Visu novāc
# docker-compose down

# Visus failus izdzēš
# docker system prune -a --volumes

# Uzbūve no jauna
# docker-compose up --build

# Jaunās lietas migrē uz esošo dockeri
# docker-compose exec web python manage.py migrate

# Super admina izveide
# docker-compose exec web python manage.py createsuperuser

# Importorte katalogu
# docker-compose exec web python manage.py import_products

# Jāieliek pārlūkprogrammā lai apskatītu vietni
# http://localhost:8000/