# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DATABASE_NAME=postgres
#       - DATABASE_USER=postgres
#       - DATABASE_PASSWORD=postgres
#       - DATABASE_HOST=db
#       - DATABASE_PORT=5432

#   db:
#     image: postgres:16
#     restart: always
#     environment:
#       POSTGRES_DB: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=postgres://kvits_user:kvits_password@db:5432/kvits_db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: kvits_user
      POSTGRES_PASSWORD: kvits_password
      POSTGRES_DB: kvits_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: