# Generated by Django 5.2 on 2025-05-05 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvitsapp', '0002_alter_product_attels_alter_product_ean13_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vārds')),
                ('last_name', models.CharField(max_length=100, verbose_name='Uzvārds')),
                ('email', models.EmailField(max_length=254, verbose_name='E-pasts')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Telefona numurs')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Uzņēmuma nosaukums')),
                ('address', models.CharField(max_length=250, verbose_name='Piegādes adrese')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Izveidots')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atjaunināts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasūtījums',
                'verbose_name_plural': 'Pasūtījumi',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Daudzums')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kvitsapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='kvitsapp.product')),
            ],
            options={
                'verbose_name': 'Pasūtījuma vienība',
                'verbose_name_plural': 'Pasūtījuma vienības',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='kvitsapp_or_created_d2655c_idx'),
        ),
    ]
